# models/product_template.py
from odoo import models, fields, api
import requests
import json
import logging

_logger = logging.getLogger(__name__)

class ProductTemplate(models.Model):
    _inherit = 'product.template'
    
    ai_insights = fields.Text(string='AI Insights', help='AI-generated insights about this product')
    ai_insights_last_updated = fields.Datetime(string='AI Insights Last Updated')
    
    def generate_ai_insights(self):
        """Generate AI insights for the product using Google Gemini"""
        for product in self:
            try:
                # Get your Gemini API key from system parameters
                gemini_api_key = self.env['ir.config_parameter'].sudo().get_param('ai_product_insights.gemini_api_key')
                
                if not gemini_api_key:
                    raise ValueError("Gemini API key not configured")
                
                # Prepare product data for AI analysis
                product_data = {
                    'name': product.name,
                    'description': product.description_sale or product.description or '',
                    'category': product.categ_id.name if product.categ_id else '',
                    'price': product.list_price,
                    'attributes': [attr.name for attr in product.attribute_line_ids.mapped('attribute_id')],
                    'tags': [tag.name for tag in product.tag_ids],
                }
                
                # Create prompt for Gemini
                prompt = f"""
                Analyze this product and provide insights in JSON format:
                
                Product: {product_data['name']}
                Description: {product_data['description']}
                Category: {product_data['category']}
                Price: ${product_data['price']}
                Attributes: {', '.join(product_data['attributes'])}
                Tags: {', '.join(product_data['tags'])}
                
                Please provide insights in the following JSON structure:
                {{
                    "key_features": ["feature1", "feature2", "feature3"],
                    "target_audience": "description of ideal customers",
                    "use_cases": ["use case 1", "use case 2"],
                    "competitive_advantages": ["advantage 1", "advantage 2"],
                    "recommendations": ["recommendation 1", "recommendation 2"],
                    "marketing_angles": ["angle 1", "angle 2"]
                }}
                """
                
                # Call Gemini API
                insights = self._call_gemini_api(gemini_api_key, prompt)
                
                # Update product with insights
                product.write({
                    'ai_insights': insights,
                    'ai_insights_last_updated': fields.Datetime.now(),
                })
                
                _logger.info(f"Generated AI insights for product: {product.name}")
                
            except Exception as e:
                _logger.error(f"Error generating AI insights for product {product.name}: {str(e)}")
                raise
    
    def _call_gemini_api(self, api_key, prompt):
        """Call Google Gemini API"""
        url = f"https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash-latest:generateContent?key={api_key}"
        
        headers = {
            'Content-Type': 'application/json',
        }
        
        data = {
            "contents": [{
                "parts": [{
                    "text": prompt
                }]
            }]
        }
        
        response = requests.post(url, headers=headers, json=data, timeout=30)
        
        if response.status_code == 200:
            result = response.json()
            if 'candidates' in result and len(result['candidates']) > 0:
                content = result['candidates'][0]['content']['parts'][0]['text']
                return content
            else:
                raise ValueError("No content generated by Gemini")
        else:
            raise ValueError(f"Gemini API error: {response.status_code} - {response.text}")
    
    def get_ai_insights_formatted(self):
        """Get formatted AI insights for display"""
        if not self.ai_insights:
            return None
            
        try:
            # Try to parse as JSON first
            insights_data = json.loads(self.ai_insights)
            return {
                'success': True,
                'data': insights_data,
                'last_updated': self.ai_insights_last_updated.strftime('%Y-%m-%d %H:%M:%S') if self.ai_insights_last_updated else None
            }
        except json.JSONDecodeError:
            # If not JSON, return as plain text
            return {
                'success': True,
                'data': {'raw_text': self.ai_insights},
                'last_updated': self.ai_insights_last_updated.strftime('%Y-%m-%d %H:%M:%S') if self.ai_insights_last_updated else None
            }
        except Exception as e:
            return {
                'success': False,
                'error': str(e)
            }